```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, fig.height = 3)
library(tidyverse)
library(lubridate)
library(scales)
library(readr)
library(gridExtra)
library(kableExtra)
library(data.table)
```


```{r}
Average_Price_Homes = read_csv("../Housing Project/CSV files/Average Sale Prices Of homes.csv") %>% mutate(`DATE` = mdy(DATE)) %>% mutate(Year = year(DATE))

Median_Price_Homes = read_csv("../Housing Project/CSV files/Median Sales Price of Homes.csv") %>% rename('DATE' = 'observation_date') %>% mutate(`DATE` = mdy(DATE)) %>% mutate(Year = year(DATE))

US_Employment_Unemployment_Rates = read_csv("../Housing Project/CSV files/US Employment Rates.csv") 

US_Household_Income = read_csv("../Housing Project/household-income-us-historical_zip/data/household-income-us-historical_csv.csv")

US_House_Price_Index = read_csv("../Housing Project/house-prices-us_zip/data/cities_csv.csv")

```

Average the ASPUS and MSPUS by Year

```{r}
Average_Price_Homes = Average_Price_Homes %>% group_by(`Year`) %>% summarize(ASPUS = mean(ASPUS)) %>% filter(`Year` >= 1967)

Median_Price_Homes = Median_Price_Homes %>% group_by(`Year`) %>% summarize(MSPUS = mean(MSPUS)) %>% filter(`Year` >= 1967)
```

Combining the Average Price and Median Price into Household Income data set

```{r}
Income_and_Housing = left_join(US_Household_Income, Average_Price_Homes, by = 'Year')
Income_and_Housing = left_join(Income_and_Housing, Median_Price_Homes, by = 'Year') %>% arrange(Year)
```

Putting it into a CSV file

```{r}
#fwrite(Income_and_Housing, "C:/Users/mrgim/Desktop/Projects/Housing Project/Data Created From R")

write.csv(Income_and_Housing, file = "C:/Users/mrgim/Desktop/Projects/Housing Project/Data Created From R/Income_and_Housing.csv", row.names=FALSE)
```

Visual Representation of the Data

```{r}
ggplot(Income_and_Housing) +
  geom_point(aes(x = Year, y = ASPUS, color = Year)) +
  geom_point(aes(x = Year, y = MSPUS, color = Year)) +
  geom_line(aes(x = Year, y = Lowest), color = 'Red') +
  geom_line(aes(x = Year, y = Second), color = 'Grey') +
  geom_line(aes(x = Year, y = Third), color = 'Black') + 
  geom_line(aes(x = Year, y = Fourth), color = 'Brown') +
  geom_line(aes(x = Year, y = `Top 5 percent`), color = 'Green') 
  
```









